server:
  port: 8611
spring:
  application:
    name: zuul
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: 172.23.127.10
      port: 8500
      discovery:
        serviceName: ${spring.application.name}    # 注册到consul的服务名称
        heartbeat: true
  redis:
    database: 0
    host: 172.23.127.10
    port: 6379
    password: 'HssMy@5Tygcs#7'
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
logging:
  config: classpath:logback-boot.xml
zuul:
  host:
    connect-timeout-millis: 35000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:        #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 25000
  ConnectTimeout: 25000


imageDirectory: '/root/files/image/'
imageMapping: '/image/**'

management:
  endpoints:
    web:
      exposure:
        include: "*"