spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB #设置允许单个文件上传的大小
      max-request-size: 50MB #设置允许上传的总的文件的大小

logging:
  config: classpath:logback-boot.xml