server:
  port: 8000
spring:
  application:
    name: ums
  #cloud
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true #是否需要注册
        instance-id: ${spring.application.name}-1 #实例id(唯一标志)
        service-name: ${spring.application.name} #服务的名称
        prefer-ip-address: true #开启ip地址注册
        ip-address: ${spring.cloud.client.ip-address} #当前服务的请求ip
        port: ${server.port} #服务的请求端口
  redis:
    database: 0
    host: 47.252.42.196
    port: 6379
    password: HssMy@5Tygcs#7
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-0xiq09n2322l690179o.mysql.rds.aliyuncs.com:3306/ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useAffectedRows=true
      username: guoxing
      password: HssMy@5Tygcs#7
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

logging:
  level:
    root: WARN
    com.upedge.ums: DEBUG
    com.upedge.test: DEBUG


files:
  image:
      local: 'D:/developer/image/'
      prefix: 'http://192.168.2.9:8611/image/'

upedge:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 50000
        loggerLevel: basic
  okhttp:
    enabled: true

rocketmq:
  name-server: localhost:9876
  producer:
    group: ums
    sendMsgTimeout: 9000

seata:
  enabled: true
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: true
  use-jdk-proxy: false
  tx-service-group: default
  service:
    vgroupMapping:
      default: default
    enable-degrade: false
    disable-global-transaction: false
    grouplist:
      default: localhost:8091


paypal:
  key: Ac9RXP4zFQ0hSxq4F_Lr_3I_yTjFUSSIxQyphhCqwvxQFdAi2_-A1z1dFL1qLelfweNcNNo-8fBi-hTl
  secret: EJ1pILHmVh4MWP1fQaPo9UwNiG9yj2nLZbaKbxhMUBeXgMY8P61gJkBgqyruP491abDyxOcRPEV1yzZY
  mode: sandbox
  url: https://api.sandbox.paypal.com